import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="h-20 w-full bg-gray-950 backdrop-blur fixed top-0 left-0 right-0 z-50 text-gray-50">
          <nav className="flex items-center justify-center h-full px-4 gap-4">
            <Link href="/">
              <p>Home</p>
            </Link>
            <Link href="/about">
              <p>About</p>
            </Link>
            <Link href="/blog">
              <p>Blog</p>
            </Link>
            <Link href="/contact">
              <p>Contact</p>
            </Link>
          </nav>
        </header>
        <main className="flex min-h-screen flex-col items-center justify-between p-24 pt-32">
          {children}
        </main>
      </body>
    </html>
  );
}
